name: å‹ç¼©å›¾ç‰‡

on:
  workflow_dispatch:  # æ‰‹åŠ¨è§¦å‘
jobs:
  build:
    name: å‹ç¼©å›¾ç‰‡
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.TOKEN }}
          compressOnly: true
          jpegQuality: "60"
          jpegProgressive: false
          pngQuality: "60"
          webpQuality: "60"

      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: "ğŸ›  å‹ç¼©å›¾ç‰‡"
          branch-suffix: timestamp
          commit-message: "ğŸ›  å‹ç¼©å›¾ç‰‡"
          body: ${{ steps.calibre.outputs.markdown }}
